version: 0.2

phases:
  pre_build:
    commands:
      # Install dependencies if needed (for example, AWS CLI or Docker)
      - echo "Installing dependencies..."
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 101538135044.dkr.ecr.ap-southeast-1.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t docker-repo:latest .
      - docker tag docker-repo:latest 101538135044.dkr.ecr.ap-southeast-1.amazonaws.com/docker-repo:latest

  post_build:
    commands:
      # Push the Docker image to Amazon ECR
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 101538135044.dkr.ecr.ap-southeast-1.amazonaws.com/docker-repo:latest
