version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      # Install dependencies if needed (for example, AWS CLI or Docker)
      - echo "Installing dependencies..."
      - aws --version
      - docker --version

  pre_build:
    commands:
      # Set the image name and tag
      - echo "Starting pre-build phase..."
      - IMAGE_REPO_NAME=my-docker-repo
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "Image tag: $IMAGE_TAG"
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      # Push the Docker image to Amazon ECR
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - '/root/.m2/**/*'
 