version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      # Install dependencies if needed (for example, AWS CLI or Docker)
      - echo "Installing dependencies..."
      - aws --version
      - docker --version

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t docker-repo:latest .
      - docker tag docker-repo:latest 101538135044.dkr.ecr.ap-southeast-1.amazonaws.com/docker-repo:latest

  post_build:
    commands:
      # Push the Docker image to Amazon ECR
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 101538135044.dkr.ecr.ap-southeast-1.amazonaws.com/docker-repo:latest

artifacts:
  files:
    - "**/*"
  dicard-paths: yes
